# Generated by Django 3.2.3 on 2021-05-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Release Version')),
                ('git_commit', models.CharField(max_length=40, verbose_name='Git Commit Hash')),
                ('built_at', models.DateTimeField(verbose_name='Built At')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
            ],
        ),
    ]
